workflows:
  only-test-workflow:
    name: Only Test Workflow
    environment:
      flutter: beta
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter emulators --launch emulator
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter analyze --no-pub
      - flutter drive --target=test_driver/app.dart
      - flutter test --no-pub
    artifacts:
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - chinnonsantos@gmail.com
      slack:
        channel: '#nudemo'
        notify_on_build_start: true
