name: nudemo
description: Nudemo
version: 1.0.0
author: Chinnon Santos <chinnonsantos@gmail.com>
homepage: https://www.chinnonsantos.com.br
repository: https://github.com/chinnonsantos/nudemo
issue_tracker: https://github.com/chinnonsantos/nudemo/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^3.2.0
  test: ^1.6.3
  qr_flutter: ^3.1.0
  carousel_slider: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true

  assets:
   - assets/images/logo_white.png

  fonts:

    - family: OpenSans
      fonts:
        # light/regular (weight: 300, style: normal/regular/plain)
        - asset: fonts/OpenSans_Light.ttf
          weight: 300
        # light/italic (weight: 300, style: light)
        - asset: fonts/OpenSans_LightItalic.ttf
          weight: 300
          style: italic

        # regular/regular (weight: 400 [default], style: normal/regular/plain [default])
        - asset: fonts/OpenSans_Regular.ttf
        # regular/italic (weight: 400, style: italic)
        - asset: fonts/OpenSans_Italic.ttf
          style: italic

        # medium/regular (weight: 500, style: normal/regular/plain)
        - asset: fonts/OpenSans_SemiBold.ttf
          weight: 500
        # medium/italic (weight: 500, style: italic)
        - asset: fonts/OpenSans_SemiBoldItalic.ttf
          weight: 500
          style: italic

        # bold/regular (weight: 700, style: normal/regular/plain)
        - asset: fonts/OpenSans_Bold.ttf
          weight: 700
        # bold/italic (weight: 700, style: italic)
        - asset: fonts/OpenSans_BoldItalic.ttf
          weight: 700
          style: italic

        # bold/regular (weight: 900, style: normal/regular/plain)
        - asset: fonts/OpenSans_ExtraBold.ttf
          weight: 900
        # bold/italic (weight: 900, style: italic)
        - asset: fonts/OpenSans_ExtraBoldItalic.ttf
          weight: 900
          style: italic

    - family: Fredericka The Great
      fonts:
        - asset: fonts/FrederickatheGreat_Regular.ttf
